### ISSUE TITLE
slog-envlogger: `RUST_LOG` with crate/module name seems to be ignored

### ISSUE THREAD

**Issue by Phrohdoh** [slog-rs/slog#203]
```
$ rustc --version
rustc 1.33.0 (2aa4c46cf 2019-02-28)

$ cargo --version
cargo 1.33.0 (f099fe94b 2019-02-12)

$ rustup --version
rustup 1.16.0 (beab5ac2b 2018-12-06)
```

See [this repo](https://github.com/Phrohdoh/repro-slogrs-std-and-env) (which I'll delete once/if this is resolved) for a repro case.

---

```rust
use slog::Drain;

fn main() {
    let decorator = slog_term::TermDecorator::new().stdout().build();
    let fmt = slog_term::CompactFormat::new(decorator).build().fuse();
    let drain = slog_envlogger::new(fmt);
    let (drain, _) = slog_async::Async::new(drain).build_with_guard(); // changing this to `build` changes nothing about the output

    let logger = slog::Logger::root(
        drain.fuse(),
        slog::o!(
            "some" => "thing",
        )
    );

    let _ = slog_stdlog::init().unwrap(); // changing this to `slog_envlogger::init` changes nothing about the output
    slog_scope::scope(&logger, slog_std_env::run);
}
```

```rust
pub fn run() {
    log::trace!("trace");
    log::debug!("debug");
    log::info!(" info");
    log::warn!(" warn");
    log::error!("error");
}
```

```toml
[package]
name = "slog_std_env"
version = "0.1.0"
authors = ["Phrohdoh"]
edition = "2018"

[dependencies]
log = "0.4.6"
slog = "2.4.1"
slog-stdlog = "3.0.2"
slog-envlogger = "2.1.0"
slog-term = "2.4.0"
slog-scope = "4.1.1"
slog-async = "2.3.0"
```

---

With the above running like so:

```
$ RUST_LOG=slog_std_env=info cargo run
```

*nothing* from the crate (neither lib nor bin) is logged.

I saw https://github.com/slog-rs/slog/issues/198 which is where I got the `build_with_guard` from, but that didn't change anything.

---

**Edit**:

Running it like so:

```
$ RUST_LOG=info cargo run
```

For example, *does* log as expected, but once a crate/module name is introduced nothing is logged.
