### ISSUE TITLE
ERRO slog-async: logger dropped messages due to channel overflow

### ISSUE THREAD

**Issue by zhuxiujia** [slog-rs/slog#257]
``` toml
slog = "2.5.2"
slog-term="2.5.0"
slog-async = "2.4.0"
```
``` rust
 let decorator = slog_term::TermDecorator::new().build();
    let drain = slog_term::CompactFormat::new(decorator).build().fuse();
    let drain = slog_async::Async::new(drain).build().fuse();
    let log = slog::Logger::root(drain, o!());
    info!(log, "Logging ready!");

    let total = 1000000;
    for i in 0..total {
        info!(log, "Logging ready!");
    }
```
